#!/usr/bin/env bash 
#
## CreatedOn: 03/10/22
## ModifiedOn: 5/24/22 
## Author: Ordained_SubGenii

cd "$(dirname "$0")" || { printf "error cd to dir..exit 1\n" &> /tmp/leftwm.log; exit 1 ; }
SCRIPTPATH="$(pwd -P)"
export SCRIPTPATH || { printf "error exporting script path..exit 1\n" &> /tmp/leftwm.log; exit 1 ; }

down_theme() {
#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
	/tmp/leftwm-theme-down 
	rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down ||  { printf "error linking down script to /tmp/leftwm-theme-down..exit 1\n" &> /tmp/leftwm.log; exit 1 ; }
}

boot_picom() {
#boot picom if it exists
if  type -P picom &>/dev/null; then
    while pgrep -i picom; do 
	pkill picom
	sleep 0.5
    done 
 (picom --config "$HOME"/.config/picom/picom.conf || exit 1) &> /dev/null & 
fi
}

theme_config() {
#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml" || { printf "error Loading Theme..exit 1" &> /tmp/leftwm.log; exit 1 ; } 
}

wallpaper_set() {
#set background  ##Modified feh --bg-scale to feh --bg-max (--bg-center, --bg-fill, --bg-tile other opts)
if type -P feh &>/dev/null; then
    feh --bg-fill "$SCRIPTPATH"/dune3.webp ||  { printf "error loading dune3.webp backgroud..exit 1\n" &> /tmp/leftwm.log; exit 1 ; }
  else 
    printf "feh command not found.exit 1\n" &> /tmp/leftwm.log
    exit 1 
fi 
}

polylaunch() {
# Test if polybar exists
if ! type -P polybar &>/dev/null; then 
  printf "polybar command not found.exit 1\n" &> /tmp/leftwm.log
  exit 1
fi
	  
# kill already running polybar instances
while pgrep -i polybar; do
    pkill polybar
    sleep 0.5
done

# launch top bar across each monitor
mapfile -t monitors < <(polybar -m | cut -d":" -f1)

i=0  
for m in "${monitors[@]}"; do
    leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
	do
	  barname="mainbar$i"
	  MONITOR=$m offsetx=$x offsety=$y width=$width polybar -c "$SCRIPTPATH"/polybar.config "$barname" >/dev/null 2>&1 | tee /tmp/polybar.log  & disown	
    	  ((i++))
        done
done
}

main() {
down_theme
boot_picom
theme_config
wallpaper_set
polylaunch
}
main
exit 0
