#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

index=0
IFS="\n" read -ra monitors <<< $(polybar -m | sed s/:.*//)
leftwm-state -q -n -t $SCRIPTPATH/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  export WSINDEX=$index MONITOR=${monitors[$index]} WIDTH=$width OFFSETX=$x OFFSETY=$y
  polybar -c $SCRIPTPATH/polybar.config leftwm &> /dev/null &
  #polybar -c $SCRIPTPATH/polybar.config leftwm -s
  let index=index+1
done

